-- MySQL Script generated by MySQL Workbench
-- Fri May  2 16:37:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema noonalibrary
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema noonalibrary
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `noonalibrary` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `noonalibrary` ;

-- -----------------------------------------------------
-- Table `noonalibrary`.`userinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noonalibrary`.`userinfo` (
  `email` VARCHAR(255) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `location` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`email`),
  ALTER TABLE userinfo DROP INDEX password;

ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `noonalibrary`.`userlibrary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noonalibrary`.`userlibrary` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bookId` INT NOT NULL,
  `ownerEmail` VARCHAR(255) NOT NULL,
  `holderEmail` VARCHAR(255) NOT NULL,
  `status` ENUM('reading', 'finished') NULL DEFAULT 'reading',
  `isLiked` TINYINT(1) NULL DEFAULT '0',
  `isLendable` TINYINT(1) NULL DEFAULT '0',
  `isBorrowed` TINYINT(1) NULL DEFAULT '0',
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `ownerEmail` (`ownerEmail` ASC) VISIBLE,
  INDEX `holderEmail` (`holderEmail` ASC) VISIBLE,
  CONSTRAINT `userlibrary_ibfk_1`
    FOREIGN KEY (`ownerEmail`)
    REFERENCES `noonalibrary`.`userinfo` (`email`),
  CONSTRAINT `userlibrary_ibfk_2`
    FOREIGN KEY (`holderEmail`)
    REFERENCES `noonalibrary`.`userinfo` (`email`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `noonalibrary`.`bookborrowrequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noonalibrary`.`bookborrowrequest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `libraryId` INT NULL DEFAULT NULL,
  `requesterEmail` VARCHAR(255) NULL DEFAULT NULL,
  `status` ENUM('requested', 'accepted', 'rejected') NULL DEFAULT 'requested',
  `requestedAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `libraryId` (`libraryId` ASC) VISIBLE,
  INDEX `requesterEmail` (`requesterEmail` ASC) VISIBLE,
  CONSTRAINT `bookborrowrequest_ibfk_1`
    FOREIGN KEY (`libraryId`)
    REFERENCES `noonalibrary`.`userlibrary` (`id`),
  CONSTRAINT `bookborrowrequest_ibfk_2`
    FOREIGN KEY (`requesterEmail`)
    REFERENCES `noonalibrary`.`userinfo` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `noonalibrary`.`bookclub`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noonalibrary`.`bookclub` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `leaderEmail` VARCHAR(255) NULL DEFAULT NULL,
  `location` VARCHAR(100) NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `time` TIME NULL DEFAULT NULL,
  `bookId` VARCHAR(50) NULL DEFAULT NULL,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `leaderEmail_UNIQUE` (`leaderEmail` ASC) VISIBLE,
  CONSTRAINT `bookclub_ibfk_1`
    FOREIGN KEY (`leaderEmail`)
    REFERENCES `noonalibrary`.`userinfo` (`email`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `noonalibrary`.`bookclubmember`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noonalibrary`.`bookclubmember` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `leaderEmail` VARCHAR(255) NOT NULL,
  `memberEmail` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `leaderEmail` (`leaderEmail` ASC) VISIBLE,
  INDEX `memberEmail` (`memberEmail` ASC) VISIBLE,
  CONSTRAINT `bookclubmember_ibfk_1`
    FOREIGN KEY (`leaderEmail`)
    REFERENCES `noonalibrary`.`bookclub` (`leaderEmail`),
  CONSTRAINT `bookclubmember_ibfk_2`
    FOREIGN KEY (`memberEmail`)
    REFERENCES `noonalibrary`.`userinfo` (`email`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `noonalibrary`.`borrowhistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noonalibrary`.`borrowhistory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bookId` VARCHAR(50) NOT NULL,
  `ownerEmail` VARCHAR(255) NOT NULL,
  `borrowerEmail` VARCHAR(255) NOT NULL,
  `borrowedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `returnedAt` DATETIME NULL DEFAULT NULL,
  `status` ENUM('borrowed', 'returned') NULL DEFAULT 'borrowed',
  PRIMARY KEY (`id`),
  INDEX `ownerEmail` (`ownerEmail` ASC) VISIBLE,
  INDEX `borrowerEmail` (`borrowerEmail` ASC) VISIBLE,
  CONSTRAINT `borrowhistory_ibfk_1`
    FOREIGN KEY (`ownerEmail`)
    REFERENCES `noonalibrary`.`userinfo` (`email`),
  CONSTRAINT `borrowhistory_ibfk_2`
    FOREIGN KEY (`borrowerEmail`)
    REFERENCES `noonalibrary`.`userinfo` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `noonalibrary`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noonalibrary`.`notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `receiverEmail` VARCHAR(255) NULL DEFAULT NULL,
  `type` VARCHAR(50) NULL DEFAULT NULL,
  `message` TEXT NULL DEFAULT NULL,
  `isRead` TINYINT(1) NULL DEFAULT '0',
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `receiverEmail` (`receiverEmail` ASC) VISIBLE,
  CONSTRAINT `notifications_ibfk_1`
    FOREIGN KEY (`receiverEmail`)
    REFERENCES `noonalibrary`.`userinfo` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `noonalibrary`.`usergenre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noonalibrary`.`usergenre` (
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `genre` VARCHAR(50) NULL DEFAULT NULL,
  INDEX `email` (`email` ASC) VISIBLE,
  CONSTRAINT `usergenre_ibfk_1`
    FOREIGN KEY (`email`)
    REFERENCES `noonalibrary`.`userinfo` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
